### ISSUE TITLE
Does this new module accept certificate based auth instead of user/password?

### ISSUE THREAD

**Issue by plz** [NetApp/ontap-rest-python#20]

**Comment by RobertBlackhart** [comment]
The ONTAP REST API does support cert/key authentication in addition to username/password. Here's an example of how to do that: https://github.com/NetApp/ontap-rest-python/blob/master/examples/python_client_library/cert_auth.py

This script does several things to set up certificates, but if you already have them set up for your user account, then all that you need to do is set up your HostConnection object like [line 131](https://github.com/NetApp/ontap-rest-python/blob/master/examples/python_client_library/cert_auth.py#L131).

**Comment by plz** [comment]
Cool thanks for the pointers
