### ISSUE TITLE
NTFS permissions through API

### ISSUE THREAD

**Issue by opperpopper** [NetApp/ontap-rest-python#21]
Hi,

We’re trying to build some automation, to offload the creation of volumes/shares to superusers, but we’re stuck at permissions.
Setting some standard AD groups in file-level permission seems impossible with the API, only share permissions can be set as far as I can see.

Also setting up audit on the CIFS share don’t seem possible.

We’re trying to replicate something like this, were using with the powershell toolkit:
    #set ntfs permission on folder
    $acl = Get-Acl \\$net_svm\$net_vol_share_name
    $AccessRule = New-Object System.Security.AccessControl.FileSystemAccessRule("DOMAIN\Netapp_SAN_Full_Administrator","FullControl", "ContainerInherit, ObjectInherit", "None", "Allow")
    $acl.SetAccessRule($AccessRule)
    $acl | Set-Acl \\$net_svm\$net_vol_share_name
    …

    #remove ACL permission
    $acl = Get-Acl \\$net_svm\$net_vol_share_name
    $AccessRule = New-Object System.Security.AccessControl.FileSystemAccessRule("Everyone","FullControl", "ContainerInherit, ObjectInherit", "None", "Allow") 
    $acl.RemoveAccessRule($AccessRule)
    $acl | Set-Acl \\$net_svm\$net_vol_share_name

AND audit:

      #Set Audit Permissions
      $AuditUser = "Everyone"
      $AuditRules = "ReadData,Delete,CreateFiles,DeleteSubdirectoriesAndFiles,ChangePermissions,Takeownership"
      $InheritType = "ContainerInherit,ObjectInherit"
      $AuditType = "Success,Failure"
      $AccessRule = New-Object System.Security.AccessControl.FileSystemAuditRule($AuditUser,$AuditRules,$InheritType,"None",$AuditType)

      $ACL = Get-Acl \\$net_svm\$net_vol_share_name
      $ACL.SetAuditRule($AccessRule)
      #Write-Host "Processing >",$TargetFolder
      $ACL | Set-Acl \\$net_svm\$net_vol_share_name

Is it possible to do this with the API or ontap-rest-python ?

**Comment by RobertBlackhart** [comment]
Here's the documentation links for the CifsShare, CifsShareAcl, and Audit resources which contain some examples using the Python netapp_ontap library:
* CifsShare: https://library.netapp.com/ecmdocs/ECMLP2858435/html/resources/cifs_share.html
* CifsShareAcl: https://library.netapp.com/ecmdocs/ECMLP2858435/html/resources/cifs_share_acl.html
* Audit: https://library.netapp.com/ecmdocs/ECMLP2858435/html/resources/audit.html

If you look through the ONTAP API documentation for the same, you can see the same examples using cURL as well: https://library.netapp.com/ecmdocs/ECMLP2862544/html/index.html

**Comment by glenndekhayser** [comment]
ONTAP admin CLI/APIs give no interface to individual files, only share level. This is by design.  

The audit is the function within ONTAP, it's not the same as what Windows would do internally (since this isn't Windows of course.)  You'll have to send that data you pull from this somewhere to munge it into the format you want. 

What is happening when you attempt to use Powershell from a Windows machine to change the ACLs?  I can't see why that wouldn't work, if you're able to do the same from Explorer.

**Comment by opperpopper** [comment]
The problem is were trying to accomplish this from a linux server, so API and/or python coding is the way we were hoping to solve this.
We have a well working powershell script, that uses the 'Import-Module Dataontap' from netapp powershell toolkit and then regular windows powershell to do ntfs permissions, but we can't directly use that on a linux server.

I guess it can't be done in a regular manor, we'll find a workaround of some kind :)
Thanks for the input.
