### ISSUE TITLE
syntax error in python_client_library list_volume.py

### ISSUE THREAD

**Issue by snkellner** [NetApp/ontap-rest-python#24]
sh-4.4# ./list_volume.py -c cluster -u admin
Traceback (most recent call last):
  File "./list_volume.py", line 24, in <module>
    from utils import Argument, parse_args, setup_logging, setup_connection
  File "/repositories/ontap-rest-python/examples/python_client_library/utils.py", line 460
    print("\033[%sB" % (self._lines_drawn - 1)).
                                               ^
SyntaxError: invalid syntax

the dot in the last line has to be removed

**Comment by RobertBlackhart** [comment]
Thanks for the report, @snkellner. Looks like this ended up in there when it shouldn't have. I'll put in a fix very soon.
