### ISSUE TITLE
Snapmirror relationship

### ISSUE THREAD

**Issue by ignaziocassano** [NetApp/ontap-rest-python#27]
Hello,  palese is it possibile an example where I can specify source and destination cluster for snapmirror relationship?
The example you wrote cannot do it.

**Comment by RobertBlackhart** [comment]
Here are the lines from the example that create the relationship:

https://github.com/NetApp/ontap-rest-python/blob/d2bc8acf062d5b52509106e462c38449acf3f734/examples/python_client_library/snapmirror_operations.py#L54-L60

If you were to change them to add cluster information, you might change 57 and 58 to:

```
dataobj['source'] = {"path": src, "cluster": {"name": "source_cluster"}}
dataobj['destination'] = {"path": dst, "cluster": {"name": "destination_cluster"}}
```

**Comment by ignaziocassano** [comment]
Many thanks
