### ISSUE TITLE
How can I list top 5 paths that a specific user consumes most for data storage?

### ISSUE THREAD

**Issue by iamdian0** [NetApp/ontap-rest-python#29]
Dear Sir/Madam,

We have would like to list out top 5 paths that a specific user consumes most for data storage to help user clean up their disk space.

It looks this might be the most relevant example script:
https://github.com/NetApp/ontap-rest-python/blob/master/examples/python_client_library/file_system_analytics.py

But just want to understand better how it works to solve our specific issue. I also appreciate it if you can add me to the slack channel as I noticed in other threads. 

Thanks,

**Comment by iamdian0** [comment]
> Thank you for reporting an issue! If you haven't already [joined our Slack community](https://netapppub.slack.com/join/shared_invite/enQtNzc0MDAwNzQ5MDc2LTE4ZDQxODgwZmY3NGUwNWM2OGVkMDlkNjZjNTEzZDYwMDMwYWM1M2E4ZmNiNzYyMWE5NmVkYTMyODdlMzhhOTI),
> then we invite you to do so. This is a great place to get help and ask questions from our community.


It says this link no longer works .. can you send me a new link to join the slack community?

**Comment by RobertBlackhart** [comment]
This should be the latest link to join Slack: https://join.slack.com/t/netapppub/shared_invite/zt-njcjx2sh-1VR2mEDvPcJAmPutOnP~mg

If you have specific questions about how the script works or how you would want to modify it for your needs, you can ask in the Slack channel. This script shows how to dump some volume-level analytics. More advanced file-level analytics may be part of future ONTAP releases.
