### ISSUE TITLE
Python list_snapshots.py KeyError: 'records'

### ISSUE THREAD

**Issue by Giack29** [NetApp/ontap-rest-python#31]
Hi,
I'm testing the use of the script list_snapshots.py in the LOD environment.
During the execution of the script, I have received this error:

[user@rhel1 rest_api]$ python list_snapshots.py -c cluster1.demo.netapp.com -v vol1_test2 -vs VS1 -u admin -p Netapp1!

Traceback (most recent call last):
  File "list_snapshots.py", line 138, in <module>
    disp_snaps(
  File "list_snapshots.py", line 75, in disp_snaps
    snaps = tmp['records']
KeyError: 'records'

I know little about Python, please can you help me?

Thanks in advance.
Giacomo

**Comment by RobertBlackhart** [comment]
The assumption in that script/function is that calling the /snapshots API returned a 200 response. I'm guessing that you got some sort of error from ONTAP instead. It would be useful to look at what the response actually contained. You could do that by inserting a line right before 75 like this:

```
print(tmp)
```

Then your output would show you what was returned and that should help.

**Comment by noorbuchi** [comment]
Cleaning up stale issues
