### ISSUE TITLE
Python script for creating vserver cifs is missing some inputs?

### ISSUE THREAD

**Issue by ashwinwriter** [NetApp/ontap-rest-python#36]
Hi,

I am running the following vserver cifs create script from python scripts section. I noticed the script contains DNS inputs, but it's missing IP & routes.destination.address input strings to be able to setup CIFS through this script. Could you advise how could I add these bits into the script ?

root@centos9 /]# python3.9 svm_operations.py -c 192.168.0.xxx -u admin
Password: 

Demonstrates SVM Operations using REST API:- 
============================================================

What SVM Operation would you like to do? [list/create/update/start/stop/delete] create
Enter the name of the SVM: smb3

Would you like to configure an Interface (y/n): n

Would you like to configure an NFS (y/n): n

Would you like to configure an CIFS (y/n): y
Enter the name of FQDN: smb3.test.com
Enter the User: administrator
Enter the password: xxxxxx
Enter the AD Name: WIN2K12R2

Would you like to configure an DNS (y/n): y
Enter the name of Domain: test.com
Enter the Server: 192.168.0.xx
{'name': 'smb3', 'language': 'c.utf_8', 'ipspace': {'name': 'Default'}, 'cifs': {'ad_domain': {'fqdn': 'smb3.test.com', 'password': 'xxxx', 'user': 'administrator'}, 'enabled': True, 'name': 'WIN2K12R2'}, 'dns': {'domains': ['test.com'], 'servers': ['192.168.0.xx']}}
{'error': {'message': 'When configuring a CIFS server on an SVM, "i**p_interface.name**", "dns.domains", "dns.servers" and "routes.destination.address" must be specified.', 'code': '13434895'}}
[root@centos9 /]#

**Comment by noorbuchi** [comment]
Cleaning up stale issues
