### ISSUE TITLE
apache_scraper.py - add caller IP and user to report

### ISSUE THREAD

**Issue by asteigerLOD** [NetApp/ontap-rest-python#37]
The apache log scraper is great for customers that slowly want to transition from ZAPI to REST over a longer time period. They can use the date filter and run the report every once in a while, to make sure that there are no ZAPI calls left, and identify calls that fell through the cracks. 

In the case of a larger customer with a bigger storage footprint and a lot of distributed automation, there could be a possibility of older scripts still being executed on an admin machine (e.g. self-made executables to provision volumes & shares). 

To better identify those ZAPI calls, it would be great to add the caller IP and user to the report. 
The data is already available in the apache logs.

I have created a version of the script that includes that. (may not be 100% perfect due to insufficient python/regex skills).
[apache_scraper_incl_user_sourceip.txt](https://github.com/NetApp/ontap-rest-python/files/8700003/apache_scraper_incl_user_sourceip.txt)

**Comment by noorbuchi** [comment]
Cleaning up stale issues. If you're interested in merging this into `main` please open a PR. Thanks!
