### ISSUE TITLE
issue with  9.8 Rest API when trying to configure SP IP address

### ISSUE THREAD

**Issue by shail-21** [NetApp/ontap-rest-python#38]
Hi,
When trying to configure cluster using rest API   in same  cluster config call trying to configure SP ip Address getting error
when trying to configure with below IP
IP Address: 10.120.15.106
Netmask: 255.255.254.0
GW: 10.120.14.1

_**Failed to create node sp network with error: The gateway is not in the same subnet defined by IP address and subnet mask/prefix length.: Failed to create node sp network with error: The gateway is not in the same subnet defined by IP address and subnet mask/prefix length.**_

**Comment by RobertBlackhart** [comment]
@shail-21 do you see the same issue when using the `sp network modify` command on the CLI?

**Comment by noorbuchi** [comment]
Cleaning up stale issues
