### ISSUE TITLE
cifs/sessions api issues

### ISSUE THREAD

**Issue by chaudhariatul** [NetApp/ontap-rest-python#43]
I'm following this documentation : https://library.netapp.com/ecmdocs/ECMLP2884821/html/#/NAS/cifs_session_collection_get
to get all the CIFS sessions for the volumes mounted, however this is the error I get.

```
{'error': {'message': '"node.uuid" is a required field',
  'code': '2',
  'target': 'node.uuid'}}
```

I need to get the output of this command using REST API.

`vserver cifs session show -active-volumes`

**Comment by noorbuchi** [comment]
can you please share more information about the code you have as well as the request/response you're getting.

You can see the requests and responses by adding this to your script:
```python
import logging
from netapp_ontap import config, utils
utils.LOG_ALL_API_CALLS = 1
utils.DEBUG = 1
logging.basicConfig(level=logging.DEBUG)
```

**Comment by chaudhariatul** [comment]
Issue resolved.
